---
- name: install haproxy package
  become: yes
  package:
    name: haproxy
    state: present

- name: rename default haproxy.cfg
  command: "mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak"

- name: config haproxy
  become: yes
  copy:
    content: |
       listen ingress-http
       bind *:80
       mode tcp
       server worker-0 worker-0.{{ cluster_domain }}:80 check
       listen ingress-https
       bind *:443
       mode tcp
       server worker-0 worker-0.{{ cluster_domain }}:443 check
       listen api
       bind *:6443
       mode tcp
       server bootstrap bootstrap.{{ cluster_domain }}:6443 check
       server master-0 master-0.{{ cluster_domain }}:6443 check
       listen machine-config-server
       bind *:22623
       mode tcp
       server bootstrap bootstrap.{{ cluster_domain }}:22623 check
       server master-0 master-0.{{ cluster_domain }}:22623 check
    dest: /etc/haproxy/haproxy.cfg

- name: add machine-config-server port in firewalld
  firewalld:
    port: 22623/tcp
    permanent: yes
    immediate: yes
    state: enabled

- name: add api port in firewalld
  firewalld:
    port: 6443/tcp
    permanent: yes
    immediate: yes
    state: enabled

- name: add ingress-https port in firewalld
  firewalld:
    port: 443/tcp
    permanent: yes
    immediate: yes
    state: enabled

- name: add ingress-http port in firewalld
  firewalld:
    port: 80/tcp
    permanent: yes
    immediate: yes
    state: enabled

- name: restart haproxy
  become: yes
  service:
    name: haproxy
    state: restarted
